---
abstract: 'WebSocket protocol'
author:
  - 'Viacheslav Tykhanovskyi, C<vti@cpan.org>.'
build_requires: {}
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: protocol-websocket
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Protocol::WebSocket:
    file: lib/Protocol/WebSocket.pm
    version: 0.13
  Protocol::WebSocket::Cookie:
    file: lib/Protocol/WebSocket/Cookie.pm
  Protocol::WebSocket::Cookie::Request:
    file: lib/Protocol/WebSocket/Cookie/Request.pm
  Protocol::WebSocket::Cookie::Response:
    file: lib/Protocol/WebSocket/Cookie/Response.pm
  Protocol::WebSocket::Frame:
    file: lib/Protocol/WebSocket/Frame.pm
  Protocol::WebSocket::Handshake:
    file: lib/Protocol/WebSocket/Handshake.pm
  Protocol::WebSocket::Handshake::Client:
    file: lib/Protocol/WebSocket/Handshake/Client.pm
  Protocol::WebSocket::Handshake::Server:
    file: lib/Protocol/WebSocket/Handshake/Server.pm
  Protocol::WebSocket::Message:
    file: lib/Protocol/WebSocket/Message.pm
  Protocol::WebSocket::Request:
    file: lib/Protocol/WebSocket/Request.pm
  Protocol::WebSocket::Response:
    file: lib/Protocol/WebSocket/Response.pm
  Protocol::WebSocket::Stateful:
    file: lib/Protocol/WebSocket/Stateful.pm
  Protocol::WebSocket::URL:
    file: lib/Protocol/WebSocket/URL.pm
requires:
  Carp: 0
  Digest::MD5: 0
  Digest::SHA1: 0
  Scalar::Util: 0
resources:
  bugtracker: https://github.com/vti/protocol-websocket/issues
  homepage: https://github.com/vti/protocol-websocket
  repository: git://github.com/vti/protocol-websocket.git
version: 0.13
x_contributors:
  - 'Jon Gentle <atrodo@atrodo.org>'
  - 'Lee Aylward <lee@laylward.com>'
  - 'Chia-liang Kao <clkao@clkao.org>'
  - 'BlueT - Matthew Lien - 練喆明 <BlueT@BlueT.org>'
  - 'Joao Orui <joao@joao.jp>'
  - 'Jonathan Barber <jonathan.barber@gmail.com>'
  - 'Toshio Ito <debug.ito@gmail.com>'
  - 'vti <viacheslav.t@gmail.com>'
